### ISSUE TITLE
Are we allowed to remove the "ring"?

### ISSUE THREAD

**Issue by awai54st** [HPCE/hpce-2016-cw6#10]
Hi,

At the moment the ring.hpp carries almost no functionality. However it still causes quite some errors when we try to add functions to the current structure. May I ask if we are allowed to remove the "ring" part?

Thank you
Best, awai54st

**Comment by m8pple** [comment]
I left just ring in so that there is an example of how other applications
would look, and I want you to keep the ring functionality in order to
keep the bare minimum of generality - to at least pretend that it is still
a general purpose simulator. 

However, you can special case the "heat" path, so that it goes into a
specialised simulator, leaving the original simulator alone - this is usually
what happens if you decide to optimise for a particular kind of input.

So there is no requirement to have a single class/function that does
all applications - you can create something different that works as
an alternative.

**Comment by awai54st** [comment]
Hi,

Does that mean we can also make a general simulator for both heat and ring, and change ring.hpp slightly to adjust to the simulator?

For example, I will add "width" and "height" members to the graph_type struct in ring, just to make sure there is no error in simulator. Would that be acceptable?

Thank you for your reply

Best, awai54st

**Comment by m8pple** [comment]
Sorry, I hadn't noticed this.

Yes - that would be a valid strategy (and closer to what I'd do in real life,
where I can't focus on one app to the exclusion of all others).

However, you may find that it limits your flexibility with heat if
you try to keep compatibility in that way. There are a number of optimisations
that can be applied to the heat application and the simulator independently,
but eventually you're likely to want to merge them at a deeper level, or
make them more explicitly coupled (e.g. for GPU work).
