### ISSUE TITLE
GPU Performance: General Question

### ISSUE THREAD

**Issue by alino95** [HPCE/hpce-2016-cw6#11]
I have a question on the GPU performance in a scenario that I came across several times.

We always said in lectures that GPU really pays back the setup costs if the kernel executes a certain number of instructions and if the iteration space is large enough to justify the need for that many parallel computational units. 

My question is: if I have an huge 2D iteration space but the inner for loop only executes a bunch of simple instructions, what should I expect? In other words, I understand that the fixed cost in setting the GPU up is high but what about the variable cost of adding one inner loop iteration? 

I know I could test it... just wondering whether somebody has a quick answer to save some time :) 

Thanks

**Comment by m8pple** [comment]
Sorry, it took me a while to get to this.

If you only have a few instructions per work-item, then:
- You are still quite likely to get a speed-up over multiple CPUs
- You may be a fair way behind the maximum possible speedup.

The overhead per extra work-item is difficult to measure, but
is probably of the order of 10-ish instructions (pulling numbers
out of the air) - so quick compared to TBB, but still noticeable.
So if you have a kernel that does 10 instructions, you could
expect that maybe 50% of the GPU's time was being wasted.
However, it is wasting that time _really_ fast, so you could still
see a big speed-up over a CPU.

So it is often worth trying to apply some agglomeration (chunking)
within the work-items, as long as you can stop the work-items
diverging too much (which is generally not a problem in a loop),
and it can also help you manage the patterns of reads and writes
by sharing data between iterations that are grouped together.

In the CW3 code, I would be inclined to try and batch things together
so that each work-item does a small local region of the world, and
extend the packing to avoid global reads and writes between
cells that have been packed together.

The caveat here is that you need to keep the number of
work-items high enough to saturate the hardware. It is
usually better to be using 100% of the GPU's processors
with 40% of that work being wasted (effective utilisation = 60%),
than to use 50% of the GPU with 0% of the work wasted
(effective utilisation = 50%).
