### ISSUE TITLE
Matlab scripts for hex and mesh

### ISSUE THREAD

**Issue by aw1513** [HPCE/hpce-2016-cw6#15]
Hello,
I have had a look at the Matlab scripts to generate hex and mesh structures. I noticed that the parameters maxTime, spaceStep and timeStep are all calculated as functions of width and height (for hex) or numCell (mesh). Does that mean that here we should not test alternate parameters? If so, why is the particular dependency on grid size chosen this way?
Or did I understand the instructions wrong and we are solely trying to optimize for a rectangular structure and the other structures are just there to complete the picture?

**Comment by m8pple** [comment]
The hex and mesh structures are also within the domain of interest, so the
idea is indeed to support them and be fast on all of them. One approach is
to just be generally fast, so your simulator can handle any type of topology
in a generic way. The other approach is to take advantage of the knowledge of the
topology, and do different things based on your knowledge of how the
graph is connected up.

As for the parameters used in the matlab scripts, that was simply because
passing parameters to matlab scripts is a bit painful from the command
line. The general goal is to support more devices for more time-steps,
and the spatial and temporal sub-sampling will tend to increase as we
do that (in order to manage bandwidth). So there is nothing special
about those relationships, they are simply to get some plausible values.
