### ISSUE TITLE
Is the count_me_in file needed for automated tests?

### ISSUE THREAD

**Issue by alino95** [HPCE/hpce-2016-cw6#17]

**Comment by m8pple** [comment]
No. I'm currently running tests for everyone who had something commited yesterday.
The count_me_in is only to see comparative performance (so if you don't have it you only
get your own times, but no-one else can see your times). So you're not seeing anything
because they haven't finished yet.

The first round of runs just always takes longer between pull and push, as I have
to react to unexpected failure modes due to interactions between submissions and
tests. I scheduled the runs based on gaps in my calendar during the week, but in
reality those will usually get filled up with meetings, so all I can really do is give
a predictable pull time.

**Comment by alino95** [comment]
Understood! Thank you very much for the quick reply. I was not sure whether to add the `count_me_in` since there was no `dt10_runs` folder in the first commit. 

Shall I add it now for todays' test results or is it too late?

**Comment by alino95** [comment]
Maybe I can just ask somebody to provide their anonymised results once out!

**Comment by m8pple** [comment]
Once I've got the Fri 15:00 run finished I'll _probably_ just do an
unscheduled run based on the latest pull (no guarantees), as the
second one is always easier. Depends when I manage to get
it done.

The `count_me_in` thing is more todo with data-privacy - from an ethical
point of view I shouldn't be sharing results without explicit permission
from the student (even if they are anonymised). Some people want to
work without having the pressure of seeing how well they are doing
in relative terms (or of having other people know fast they are!)

So I'm quite happy for you to get results off someone else.
