### ISSUE TITLE
Asserting Ref/User Statistics - Why?

### ISSUE THREAD

**Issue by akasture1** [HPCE/hpce-2016-cw6#20]
Hi,

I had a slight doubt regarding the output statistics aspect of the simulator. In the readme.md file, you say the following:

During each time step the simulator produces a summary of statistics, counting how many nodes and devices were in each state. The idea is that **this can be used to find patterns and problems in the hardware utilisation**.

One thing the simulator produces is a stream of statistics, explaining what the devices and edges were doing in each hardware "time step". **This should match the output of the reference simulator**.

My partner and I have been working through some possible solutions that, in theory, are likely to improve the wall-clock time taken for the 2D grid to evolve from start to finish. However, we are often held back by the requirement that the reference and user statistics need to match. 

My question is as follows: Do the maintenance of statistics, in the exact same format, not assert a restriction on the evolution of the grid in time? For example, if the statistics are saying that at step k, we observe N blocked nodes and M idle nodes, does this not require us to ensure that our user simulator also maintains this exact scenario? What if I wanted to accelerate this evolution ? Are the statistics not there to help us identify patterns in the hardware utilisation, and consequently allow us to address the bottlenecks? Or is this requirement intentional as part of the hardware model itself ?

Thank You,
Anand

**Comment by m8pple** [comment]
Because this is a [behavioural simulator](https://github.com/HPCE/hpce-2016-cw6#the-poets-simulator), the hardware statistics are the
actual answer, which is why they need to match. So they are not there to help you
optimise (though they might provide useful info), they are there to provide the
actual answers.

So you are correct that producing the same statistics may (severely) impact your ability to
optimise, but that is because the statistics are part of the output.

If this were only an application-level simulator, then there are definitely way of evolving
the application much faster if you ignore the hardware. I've previously built a multi-core+MPI
simulator for the application side of things, so I can already do the application simulation
very fast (although it requires a cluster, and isn't GPU accelerated). In that version the
application evolves forwards in a very different way, with messages delivered in an order that
is very unrelated to how it would be delivered in actual hardware.

What I don't have is something that can help me estimate how long the hardware is going
to take to run in real hardware. It's quite easy to come up with an application that works
well in a simulator that only models the semantics of an asynchronous machine, but
has terrible performance once you start to include finite transmission delays and the
need to map each application device to a physical node.

The difference is very similar to the difference between an ARM core, SimpleScalar,
and QEMU:

- [QEMU](https://en.wikipedia.org/wiki/QEMU#ARM) is designed to simulate an ARM
  only at the ISA level, and tries to just run ARM programs as fast as possible.
  It doesn't try to model an actual piece of silicon, so programs which are fast in
  QEMU may be slow in an ARM processor, and vice-versa.

- [SimpleScalar](http://www.simplescalar.com/overview.html) is designed to model
  low-level processor features while an ARM programs executes, estimating how long
  it took to execute and helping you see whether there are any performance issues.

- An ARM processor is the eventual target hardware, but until you have the piece of
  silicon, you would use QEMU to debug your programs, and SimpleScalar to debug your
  performance. If you wait until you've got actual hardware, you're going to have to delay
  shipping of any software till much later.
