### ISSUE TITLE
Kernel implementation of rendering works for rect and mesh topologies but not hex

### ISSUE THREAD

**Issue by pierrezaza** [HPCE/hpce-2016-cw6#24]
I have transferred the code used to render each slice of the graph in a JPEG to an OpenCL kernel. For rect and mesh topologies, the output is correct, however for a hex shape, I get a very strange output: the image/animation has the same size as the reference one, but it contains two identical versions of the reference animation, squished into the reference size. Please have a look at the attached files, it will be easier to understand. The files attached ([heat.zip](https://github.com/HPCE/hpce-2016-cw6/files/634566/heat.zip)) were produced using the following commands:

```
octave src/tools/generate_heat_hex.m  > w/heat${SIZE}.graph
echo "Executing Reference"
time bin/ref/simulator --log-level 0 w/heat${SIZE}.graph w/stats${SIZE}.txt  w/heat${SIZE}.mjpeg
echo "Executing Pierre"
time bin/user/pva13/user_simulator_v0_p --log-level 0 w/heat${SIZE}.graph w/stats${SIZE}_user.txt  w/heat${SIZE}_user.mjpeg
```

and it the matlab script:

```
w=127;
h=65;
pixW=min(256,w*3);
pixH=min(128,w*3);
maxTime=ceil(2*sqrt(w*h));
spaceFrac = max(1, w*h/8192);
timeStep=min(1, floor( sqrt(w) ));
minHeat=-8000;
maxHeat=+8000;
```

My question is: is this likely to be a mistake in my code or something that I am not in control of? I don't really get why it works for rect and mesh but not for hex...

**Comment by m8pple** [comment]
I'm not exactly sure, but my guess would be that you're assuming something
about the width and height of the output image that are not true. It's noticeable
that in the above hex grid the weight is twice the height, but you're getting two
images side-by side.

Try modifying the hex generator to produce a graph that has pixW==pixH and
see if you get the right result. Then try modifying it to use pixW==pixH+5. If you
get weird shearing effects, then that is probably where the problem is.

**Comment by pierrezaza** [comment]
I'll give a try, thank you :)

**Comment by pierrezaza** [comment]
Fixed it, I was indexing some buffers using `[y*h+x]` instead of `[y*w+x]`! Thank you very much @m8pple!
