### ISSUE TITLE
Parallel Simulator

### ISSUE THREAD

**Issue by a-camuto** [HPCE/hpce-2016-cw6#25]
We've been going around in circles trying to find a way to parallelise simulator.hpp. We are losing our minds trying to find a solution. help.

**Comment by plus44** [comment]
same bro...

**Comment by m8pple** [comment]
I assume you've identifed [this part](https://github.com/HPCE/hpce-2016-cw6/blob/master/include/simulator.hpp#L201-L213) as one of the main driving parts, where a fair amount of time
is spent on the simulation (rather than output) side.

Consider this loop:

        for(unsigned i=0; i<m_nodes.size(); i++){
            active = step_node(i, &m_nodes[i]) || active;
        }

Can it be parallelised? Looking at the different components:
- there is clearly a loop-carried dependency via `active1`, but can that be by passed?
- The step_node function is applied to each point `i` in the iteration space. Is each
   point independent? Looking in step_node will allow you to unpick the dependencies.
- Is there enough work in each call to step_node? Does it vary on each iteration? Can you
   apply chunking to increase the work per task?

Then look at the [other loop](https://github.com/HPCE/hpce-2016-cw6/blob/master/include/simulator.hpp#L205-L207). This is more complicated, as if you sketch the dependencies
in step_edge there will be conflicting writes from some edges to the same node.
So you have a couple of options:
- Use some method to make sure that all edges that write to a given node will not
   execute at the same time.
- Use a different iteration space to iterate over the edges. How else can you make
  sure that every edge is processed within a step, while also making sure that all
  edges that write to a given node are processed in the same task (or iteration point)?

**Comment by a-camuto** [comment]
Thank you so much for your help !
