### ISSUE TITLE
Test script

### ISSUE THREAD

**Issue by sagarpatel9410** [HPCE/hpce-2016-cw6#30]
I am trying to run rect_n40000_t2048_ds8_dt32, am I right in saying that this will create a graph in this form:

`bin/tools/generate_heat_rect 40000 2048 32 8 `

When I try to recreate this on my instance I get this error:

![image](https://cloud.githubusercontent.com/assets/11628383/21033650/da160088-bda9-11e6-8b52-3b50674da3ee.png)

This is attempting to read a graph but failing to load it, upon further inspection the .graph output is empty, am I doing something incorrect in the generation of the graph?

**Comment by m8pple** [comment]
Bear in mind that the program takes the width(=height), so you're trying to
generate a 1.6 billion node graph with ~12 billion edges. Maybe POETS
will scale to such sizes, but I don't expect you to :)

I created it as a sqrt(40k)*sqrt(40k) graph.

It only just occured to me that you can't see the exact inputs, as I pre-generate
the inputs and reference outputs in order to save time on AWS. I'll add them to
the repo, just for completeness.
