### ISSUE TITLE
Broken pipe

### ISSUE THREAD

**Issue by jeremych1000** [HPCE/hpce-2016-cw6#35]
When benchmarking on AWS, I've run into some issues where the benchmarking script just stops, but doesn't exit with any errors.

```
Running simulator...
Running all implementations for ./inputs/gen_hex_n1000_t64_ds7_dt2.graph
0 1 2 3 4
Running all implementations for ./inputs/gen_hex_n16000_t10000_ds10_dt1000.graph
0 1 2 3 Write failed: Broken pipe
```

The broken pipe appears after terminating using CTRL+C, when I think it has gone too long without going onto the next benchmarking item.

Anyone have any idea what causes this?

**Comment by m8pple** [comment]
It usually means that one side has crashed, or otherwise exited. If you're pressing ctrl-c, it may just be that the receiving side is getting killed before the sending side. As far as i know, the order in which the processes are killed is not specified, so you may get different results each time.

As long as it only happens on ctrl-c, you should be fine.
